### ISSUE TITLE
匹配规则怎么写也不对

### ISSUE THREAD

**Issue by mosesyu95** [didi/falcon-log-agent#10]
日志格式这样，谁会写匹配规则，帮忙来个示例。谢谢。统计200访问量
192.168.0.254 - - [14/Aug/2018:17:25:19 +0800] "GET /admin.php HTTP/1.1" 200 34 "http://test.svsse.dev/admin.php" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:56.0) Gecko/20100101 Firefox/56.0" "103.254.65.210"

**Comment by GaoJiasheng** [comment]
学学正则表达式哈~
