### ISSUE TITLE
日志么有报错，但是为啥没有上报到agent数据呢?

### ISSUE THREAD

**Issue by lanyulei** [didi/falcon-log-agent#11]
strategy.dev.json 如下：
[
    {
        "id":1,
        "name":"test_nginx_500",
        "file_path":"/home/lanyulei/go/go_projects/open-falcon/log_agent/log/test.log",
        "time_format":"yyyy-mm-dd HH:MM:SS",
        "pattern":"error",
        "exclude":"",
        "step":10,
        "tags":{
            "error":"test_error"
        },
        "func":"cnt",
        "degree":6,
        "comment":"我是备注"
    }
]

相关的日志信息如下：
2018-08-14 18:30:00.442322 DEBUG metric/metric.go:96 self monit [metric:log.agent.push.err.cnt][tms:1534242600][value:0]
2018-08-14 18:30:00.442331 DEBUG metric/metric.go:97 self monit [metric:log.agent.read.line.cnt][tms:1534242600][value:&{{{0 0} 0 0 0 0} map[/home/lanyulei/go/go_projects/open-falcon/log_agent/log/test.log:50]}]
2018-08-14 18:30:00.442416 DEBUG metric/metric.go:98 self monit [metric:log.agent.drop.line.cnt][tms:1534242600][value:&{{{0 0} 0 0 0 0} map[/home/lanyulei/go/go_projects/open-falcon/log_agent/log/test.log:0]}]
2018-08-14 18:30:00.442433 DEBUG metric/metric.go:99 self monit [metric:log.agent.analysis.cnt][tms:1534242600][value:&{{{0 0} 0 0 0 0} map[/home/lanyulei/go/go_projects/open-falcon/log_agent/log/test.log:50]}]
2018-08-14 18:30:00.442448 DEBUG metric/metric.go:100 self monit [metric:log.agent.analysis.succ][tms:1534242600][value:&{{{0 0} 0 0 0 0} map[]}]

请大神指教啊。

**Comment by lanyulei** [comment]
日志格式等配置， 都是正确的。

**Comment by lanyulei** [comment]
我的是ubuntu的系统。

**Comment by GaoJiasheng** [comment]
读到50行日志，分析了50行日志。但是匹配到0行。
可以check下，是不是pattern和tags写错了。（btw：tags也是会去正则匹配的）

@lanyulei

**Comment by lanyulei** [comment]
tags的匹配规律是啥呢， 我直接在配置文件中是写死的。但是为啥不行呢。

**Comment by mosesyu95** [comment]
[
    {
        "id":1,
        "name":"gfagagsdsafgdsaf",
        "file_path":"/usr/local/open-falcon/falcon-agent/6.2.5/var/app.log",
        "time_format":"yyyy/mm/dd HH:MM:SS",
        "pattern":".*",
        "exclude":"",
        "step":10,
        "tags":{
        },
        "func":"sum",
        "degree":6,
        "comment":"我是备注"
    }
]
我的写成这样也没有匹配上

**Comment by mosesyu95** [comment]
![image](https://user-images.githubusercontent.com/22955185/44140790-c0982134-a0ad-11e8-8f06-632f622b8be1.png)
我在push.go 加了这个，并没有打印出来

**Comment by lanyulei** [comment]
@mosesyu95   我按照你的方式也成功上报数据了。但是这样配置不是很好啊。如何完善呢。

**Comment by lanyulei** [comment]
fatal error: concurrent map read and map write   总是报这个错误 @GaoJiasheng

**Comment by mosesyu95** [comment]
使用的是regexp包这个正则匹配规则，你百度下 “go regexp “ 看下正则规则怎么写 ，
你说的报错看下其他issue里面有我的答案

**Comment by GaoJiasheng** [comment]
加了一个api，可以用来check采集策略写的是否正确。

可以看下：https://github.com/didi/falcon-log-agent#%E6%A3%80%E9%AA%8C%E6%97%A5%E5%BF%97%E6%A0%BC%E5%BC%8F

**Comment by NICK-DUAN** [comment]
> 读到50行日志，分析了50行日志但是匹配到0行。
> 可以检查下，是不是图案和标签写错了（顺便说一句：标签也是会去正则匹配的）。
> 
> @lanyulei

同样的问题，我也无法上报，经过暴露的API检测后，策略生效，并且日志信息能准确命中，但是就是无法上报。
**strategy.json配置**
`[
    {
        "id":1,
        "name":"测试",
        "file_path":"/data/release/ops_order_system/ops_order/logs/order_operate.log",
        "time_format":"yyyy-mm-dd HH:MM:SS",
        "pattern":"nickduan",
        "exclude":"ordertype",
        "step":10,
        "tags":{
        },
        "func":"cnt",
        "degree":6,
        "comment":"我是备注"
    },
    {
        "id":1,
        "name":"测试",
        "file_path":"/data/release/ops_order_system/ops_order/logs/order_operate.log",
        "time_format":"yyyy-mm-dd HH:MM:SS",
        "pattern":"nickduan",
        "exclude":"ordertype",
        "step":10,
        "tags":{
        },
        "func":"cnt",
        "degree":6,
        "comment":"我是备注"
    }
]
`
测试返回：
`curl -s -XPOST localhost:8003/check -d  'log=2019-02-26 17:10:55,753 - views.py - show_add_ordertype_condition - 104 - INFO - nickduan ready to add an ordertype, getting params list, species_list, user_list, flow ids' | python -m json.tool`
**命中时的返回结果**
`{
    "body": [
        {
            "detail": {
                "pattern_": "nickduan",
                "time_": "2019-02-26 17:10:55"
            },
            "strategy": {
                "comment": "\u6211\u662f\u5907\u6ce8",
                "degree": 6,
                "exclude": "",
                "file_path": "/data/release/ops_order_system/ops_order/logs/order_operate.log",
                "func": "cnt",
                "id": 1,
                "name": "\u6d4b\u8bd5",
                "parse_succ": true,
                "pattern": "nickduan",
                "step": 10,
                "tags": {},
                "time_format": "yyyy-mm-dd HH:MM:SS"
            }
        }
    ],
    "matched": true
}
`
**agent info日志**
`[ops@gzqc-172_24_31_4-null falcon-log-agent]$ tail -50 log/INFO.log 
2019-02-26 17:31:37.901331 INFO patrol/patrol.go:22 agent mem used : 49MB, percent : 4%
2019-02-26 17:31:47.908127 INFO patrol/patrol.go:22 agent mem used : 33MB, percent : 3%
2019-02-26 17:31:57.908350 INFO patrol/patrol.go:22 agent mem used : 33MB, percent : 3%
2019-02-26 17:32:07.908502 INFO patrol/patrol.go:22 agent mem used : 33MB, percent : 3%
2019-02-26 17:32:17.908691 INFO patrol/patrol.go:22 agent mem used : 33MB, percent : 3%
2019-02-26 17:32:27.908891 INFO patrol/patrol.go:22 agent mem used : 33MB, percent : 3%
2019-02-26 17:32:37.894072 INFO strategy/update.go:20 [1551173557]Update Strategy start
2019-02-26 17:32:37.894220 INFO strategy/get_config.go:77 load config success from cfg/strategy.json
2019-02-26 17:32:37.894361 INFO strategy/update.go:29 [1551173557]Get my Strategy success, num : [2]
2019-02-26 17:32:37.894370 INFO strategy/update.go:36 [1551173557]Update Strategy end
2019-02-26 17:32:37.898625 INFO worker/counter.go:273 Updating global count
2019-02-26 17:32:37.898637 INFO worker/counter.go:304 Update global count done, [del:0][update:0]
2019-02-26 17:32:37.911186 INFO patrol/patrol.go:22 agent mem used : 49MB, percent : 4%
2019-02-26 17:32:47.911383 INFO patrol/patrol.go:22 agent mem used : 49MB, percent : 4%
2019-02-26 17:32:57.911664 INFO patrol/patrol.go:22 agent mem used : 49MB, percent : 4%
2019-02-26 17:33:07.911807 INFO patrol/patrol.go:22 agent mem used : 49MB, percent : 4%
2019-02-26 17:33:17.912043 INFO patrol/patrol.go:22 agent mem used : 49MB, percent : 4%
2019-02-26 17:33:27.912243 INFO patrol/patrol.go:22 agent mem used : 49MB, percent : 4%
2019-02-26 17:33:37.898805 INFO strategy/update.go:20 [1551173617]Update Strategy start
2019-02-26 17:33:37.898962 INFO strategy/get_config.go:77 load config success from cfg/strategy.json
2019-02-26 17:33:37.899086 INFO strategy/update.go:29 [1551173617]Get my Strategy success, num : [2]
2019-02-26 17:33:37.899094 INFO strategy/update.go:36 [1551173617]Update Strategy end
2019-02-26 17:33:37.900928 INFO worker/counter.go:273 Updating global count
2019-02-26 17:33:37.900943 INFO worker/counter.go:304 Update global count done, [del:0][update:0]
2019-02-26 17:33:37.913093 INFO patrol/patrol.go:22 agent mem used : 33MB, percent : 3%
2019-02-26 17:33:47.913243 INFO patrol/patrol.go:22 agent mem used : 33MB, percent : 3%
2019-02-26 17:33:57.913487 INFO patrol/patrol.go:22 agent mem used : 33MB, percent : 3%
2019-02-26 17:34:07.913639 INFO patrol/patrol.go:22 agent mem used : 33MB, percent : 3%
2019-02-26 17:34:17.913805 INFO patrol/patrol.go:22 agent mem used : 33MB, percent : 3%
2019-02-26 17:34:27.913950 INFO patrol/patrol.go:22 agent mem used : 33MB, percent : 3%
2019-02-26 17:34:37.901633 INFO strategy/update.go:20 [1551173677]Update Strategy start
`
**调用api接口返回的上报结果**
`{u'counters': {}}`

能否帮忙看一下

**Comment by GaoJiasheng** [comment]
> @GaoJiasheng @mosesyu95 @lanyulei
> 解决了吗？
> 
> 同样的问题，我也无法上报，经过暴露的API检测后，策略生效，并且日志信息能准确命中，但是就是无法上报。
> 
> #### strategy.json配置
> `[ { "id":1, "name":"测试", "file_path":"/data/release/ops_order_system/ops_order/logs/order_operate.log", "time_format":"yyyy-mm-dd HH:MM:SS", "pattern":"nickduan", "exclude":"ordertype", "step":10, "tags":{ }, "func":"cnt", "degree":6, "comment":"我是备注" }, { "id":1, "name":"测试", "file_path":"/data/release/ops_order_system/ops_order/logs/order_operate.log", "time_format":"yyyy-mm-dd HH:MM:SS", "pattern":"nickduan", "exclude":"ordertype", "step":10, "tags":{ }, "func":"cnt", "degree":6, "comment":"我是备注" } ] `
> 
> #### 测试返回的代码：
> `curl -s -XPOST localhost:8003/check -d 'log=2019-02-26 17:10:55,753 - views.py - show_add_ordertype_condition - 104 - INFO - nickduan ready to add an ordertype, getting params list, species_list, user_list, flow ids' | python -m json.tool`
> 
> **命中时的返回结果**
> 
> `{ "body": [ { "detail": { "pattern_": "nickduan", "time_": "2019-02-26 17:10:55" }, "strategy": { "comment": "\u6211\u662f\u5907\u6ce8", "degree": 6, "exclude": "", "file_path": "/data/release/ops_order_system/ops_order/logs/order_operate.log", "func": "cnt", "id": 1, "name": "\u6d4b\u8bd5", "parse_succ": true, "pattern": "nickduan", "step": 10, "tags": {}, "time_format": "yyyy-mm-dd HH:MM:SS" } } ], "matched": true } `
> 
> #### agent info日志
> `[ops@gzqc-172_24_31_4-null falcon-log-agent]$ tail -50 log/INFO.log 2019-02-26 17:31:37.901331 INFO patrol/patrol.go:22 agent mem used : 49MB, percent : 4% 2019-02-26 17:31:47.908127 INFO patrol/patrol.go:22 agent mem used : 33MB, percent : 3% 2019-02-26 17:31:57.908350 INFO patrol/patrol.go:22 agent mem used : 33MB, percent : 3% 2019-02-26 17:32:07.908502 INFO patrol/patrol.go:22 agent mem used : 33MB, percent : 3% 2019-02-26 17:32:17.908691 INFO patrol/patrol.go:22 agent mem used : 33MB, percent : 3% 2019-02-26 17:32:27.908891 INFO patrol/patrol.go:22 agent mem used : 33MB, percent : 3% 2019-02-26 17:32:37.894072 INFO strategy/update.go:20 [1551173557]Update Strategy start 2019-02-26 17:32:37.894220 INFO strategy/get_config.go:77 load config success from cfg/strategy.json 2019-02-26 17:32:37.894361 INFO strategy/update.go:29 [1551173557]Get my Strategy success, num : [2] 2019-02-26 17:32:37.894370 INFO strategy/update.go:36 [1551173557]Update Strategy end 2019-02-26 17:32:37.898625 INFO worker/counter.go:273 Updating global count 2019-02-26 17:32:37.898637 INFO worker/counter.go:304 Update global count done, [del:0][update:0] 2019-02-26 17:32:37.911186 INFO patrol/patrol.go:22 agent mem used : 49MB, percent : 4% 2019-02-26 17:32:47.911383 INFO patrol/patrol.go:22 agent mem used : 49MB, percent : 4% 2019-02-26 17:32:57.911664 INFO patrol/patrol.go:22 agent mem used : 49MB, percent : 4% 2019-02-26 17:33:07.911807 INFO patrol/patrol.go:22 agent mem used : 49MB, percent : 4% 2019-02-26 17:33:17.912043 INFO patrol/patrol.go:22 agent mem used : 49MB, percent : 4% 2019-02-26 17:33:27.912243 INFO patrol/patrol.go:22 agent mem used : 49MB, percent : 4% 2019-02-26 17:33:37.898805 INFO strategy/update.go:20 [1551173617]Update Strategy start 2019-02-26 17:33:37.898962 INFO strategy/get_config.go:77 load config success from cfg/strategy.json 2019-02-26 17:33:37.899086 INFO strategy/update.go:29 [1551173617]Get my Strategy success, num : [2] 2019-02-26 17:33:37.899094 INFO strategy/update.go:36 [1551173617]Update Strategy end 2019-02-26 17:33:37.900928 INFO worker/counter.go:273 Updating global count 2019-02-26 17:33:37.900943 INFO worker/counter.go:304 Update global count done, [del:0][update:0] 2019-02-26 17:33:37.913093 INFO patrol/patrol.go:22 agent mem used : 33MB, percent : 3% 2019-02-26 17:33:47.913243 INFO patrol/patrol.go:22 agent mem used : 33MB, percent : 3% 2019-02-26 17:33:57.913487 INFO patrol/patrol.go:22 agent mem used : 33MB, percent : 3% 2019-02-26 17:34:07.913639 INFO patrol/patrol.go:22 agent mem used : 33MB, percent : 3% 2019-02-26 17:34:17.913805 INFO patrol/patrol.go:22 agent mem used : 33MB, percent : 3% 2019-02-26 17:34:27.913950 INFO patrol/patrol.go:22 agent mem used : 33MB, percent : 3% 2019-02-26 17:34:37.901633 INFO strategy/update.go:20 [1551173677]Update Strategy start `
> 
> #### 调用api接口返回的上报结果
> `{u'counters': {}}`
> 
> 头疼

你的策略没问题，日志也没问题，看起来一切正常。
但是从日志看，agent没有检测到你的日志的滚动，可以check下自监控的指标，看看读取的日志行数，以及分析成功的日志行数。
如果是读取日志失败，可能有如下几个原因：
- 弄错文件名了
- agent是用普通用户启动的，没有读取日志文件的权限
- 日志没有在持续的滚动（每一个周期的滚动只会产生一个点，多个周期有日志才会连成一条线）

**Comment by NICK-DUAN** [comment]
> > @GaoJiasheng @mosesyu95 @lanyulei
> > 解决了吗？
> > 同样的问题，我也无法上报，经过暴露的API检测后，策略生效，并且日志信息能准确命中，但是就是无法上报。
> > #### strategy.json配置
> > `[ { "id":1, "name":"测试", "file_path":"/data/release/ops_order_system/ops_order/logs/order_operate.log", "time_format":"yyyy-mm-dd HH:MM:SS", "pattern":"nickduan", "exclude":"ordertype", "step":10, "tags":{ }, "func":"cnt", "degree":6, "comment":"我是备注" }, { "id":1, "name":"测试", "file_path":"/data/release/ops_order_system/ops_order/logs/order_operate.log", "time_format":"yyyy-mm-dd HH:MM:SS", "pattern":"nickduan", "exclude":"ordertype", "step":10, "tags":{ }, "func":"cnt", "degree":6, "comment":"我是备注" } ] `
> > #### 测试返回的代码：
> > `curl -s -XPOST localhost:8003/check -d 'log=2019-02-26 17:10:55,753 - views.py - show_add_ordertype_condition - 104 - INFO - nickduan ready to add an ordertype, getting params list, species_list, user_list, flow ids' | python -m json.tool`
> > **命中时的返回结果**
> > `{ "body": [ { "detail": { "pattern_": "nickduan", "time_": "2019-02-26 17:10:55" }, "strategy": { "comment": "\u6211\u662f\u5907\u6ce8", "degree": 6, "exclude": "", "file_path": "/data/release/ops_order_system/ops_order/logs/order_operate.log", "func": "cnt", "id": 1, "name": "\u6d4b\u8bd5", "parse_succ": true, "pattern": "nickduan", "step": 10, "tags": {}, "time_format": "yyyy-mm-dd HH:MM:SS" } } ], "matched": true } `
> > #### agent info日志
> > `[ops@gzqc-172_24_31_4-null falcon-log-agent]$ tail -50 log/INFO.log 2019-02-26 17:31:37.901331 INFO patrol/patrol.go:22 agent mem used : 49MB, percent : 4% 2019-02-26 17:31:47.908127 INFO patrol/patrol.go:22 agent mem used : 33MB, percent : 3% 2019-02-26 17:31:57.908350 INFO patrol/patrol.go:22 agent mem used : 33MB, percent : 3% 2019-02-26 17:32:07.908502 INFO patrol/patrol.go:22 agent mem used : 33MB, percent : 3% 2019-02-26 17:32:17.908691 INFO patrol/patrol.go:22 agent mem used : 33MB, percent : 3% 2019-02-26 17:32:27.908891 INFO patrol/patrol.go:22 agent mem used : 33MB, percent : 3% 2019-02-26 17:32:37.894072 INFO strategy/update.go:20 [1551173557]Update Strategy start 2019-02-26 17:32:37.894220 INFO strategy/get_config.go:77 load config success from cfg/strategy.json 2019-02-26 17:32:37.894361 INFO strategy/update.go:29 [1551173557]Get my Strategy success, num : [2] 2019-02-26 17:32:37.894370 INFO strategy/update.go:36 [1551173557]Update Strategy end 2019-02-26 17:32:37.898625 INFO worker/counter.go:273 Updating global count 2019-02-26 17:32:37.898637 INFO worker/counter.go:304 Update global count done, [del:0][update:0] 2019-02-26 17:32:37.911186 INFO patrol/patrol.go:22 agent mem used : 49MB, percent : 4% 2019-02-26 17:32:47.911383 INFO patrol/patrol.go:22 agent mem used : 49MB, percent : 4% 2019-02-26 17:32:57.911664 INFO patrol/patrol.go:22 agent mem used : 49MB, percent : 4% 2019-02-26 17:33:07.911807 INFO patrol/patrol.go:22 agent mem used : 49MB, percent : 4% 2019-02-26 17:33:17.912043 INFO patrol/patrol.go:22 agent mem used : 49MB, percent : 4% 2019-02-26 17:33:27.912243 INFO patrol/patrol.go:22 agent mem used : 49MB, percent : 4% 2019-02-26 17:33:37.898805 INFO strategy/update.go:20 [1551173617]Update Strategy start 2019-02-26 17:33:37.898962 INFO strategy/get_config.go:77 load config success from cfg/strategy.json 2019-02-26 17:33:37.899086 INFO strategy/update.go:29 [1551173617]Get my Strategy success, num : [2] 2019-02-26 17:33:37.899094 INFO strategy/update.go:36 [1551173617]Update Strategy end 2019-02-26 17:33:37.900928 INFO worker/counter.go:273 Updating global count 2019-02-26 17:33:37.900943 INFO worker/counter.go:304 Update global count done, [del:0][update:0] 2019-02-26 17:33:37.913093 INFO patrol/patrol.go:22 agent mem used : 33MB, percent : 3% 2019-02-26 17:33:47.913243 INFO patrol/patrol.go:22 agent mem used : 33MB, percent : 3% 2019-02-26 17:33:57.913487 INFO patrol/patrol.go:22 agent mem used : 33MB, percent : 3% 2019-02-26 17:34:07.913639 INFO patrol/patrol.go:22 agent mem used : 33MB, percent : 3% 2019-02-26 17:34:17.913805 INFO patrol/patrol.go:22 agent mem used : 33MB, percent : 3% 2019-02-26 17:34:27.913950 INFO patrol/patrol.go:22 agent mem used : 33MB, percent : 3% 2019-02-26 17:34:37.901633 INFO strategy/update.go:20 [1551173677]Update Strategy start `
> > #### 调用api接口返回的上报结果
> > `{u'counters': {}}`
> > 头疼
> 
> 你的策略没问题，日志也没问题，看起来一切正常。
> 但是从日志看，agent没有检测到你的日志的滚动，可以check下自监控的指标，看看读取的日志行数，以及分析成功的日志行数。
> 如果是读取日志失败，可能有如下几个原因：
> 
> * 弄错文件名了
> * agent是用普通用户启动的，没有读取日志文件的权限
> * 日志没有在持续的滚动（每一个周期的滚动只会产生一个点，多个周期有日志才会连成一条线）

不好意思，我找到原因了。没有及时关掉。
