### ISSUE TITLE
这个一个buge还是怎么回事

### ISSUE THREAD

**Issue by mosesyu95** [didi/falcon-log-agent#13]
最终结果为0是不会上传数据吗？
![image](https://user-images.githubusercontent.com/22955185/44243433-a4e5f100-a201-11e8-8a6a-8d1254630f78.png)

**Comment by GaoJiasheng** [comment]
看图上，这个蓝色的线，应该是1吧。。。

**Comment by GaoJiasheng** [comment]
嗯，对的，falcon-plus从0.2开始，就已经支持非周期上报数据了呢。
https://github.com/open-falcon/rrdlite/pull/3/files

**Comment by nomyself** [comment]
匹配到 0 条不上报这种报警策略不好设置吧？典型的错误日志场景，一般都是突发一堆，正常都是 0。

**Comment by tonglin0325** [comment]
可是使用open-falcon的nodata模块进行补零
