### ISSUE TITLE
make pack没有生成tar文件，直接control start报./falcon-log-agent: 1: ./falcon-log-agent: Syntax error: word unexpected (expecting ")")

### ISSUE THREAD

**Issue by tonglin0325** [didi/falcon-log-agent#15]
make pack没有生成tar文件，直接control start报./falcon-log-agent: 1: ./falcon-log-agent: Syntax error: word unexpected (expecting ")")

**Comment by GaoJiasheng** [comment]
我这边没有问题呀，你更新到最新版代码再试试？
btw：你是什么环境？

**Comment by tonglin0325** [comment]
开发环境是Ubuntu 16.04,已经git pull到最新的代码还是不行

**Comment by mdh67899** [comment]
应该是这个comit https://github.com/didi/falcon-log-agent/commit/d9b8d81b04bf5f6bf356a8d0f6c0d251579ee242 的原因，Makefile中删掉压缩包的名字，make build没问题， make pack和make all的时候没办法打成压缩包

**Comment by tonglin0325** [comment]
修改了Makefile文件之后可以打包了,但是在测试的时候正则无法测试通过
curl -s -XPOST localhost:8003/check -d  'log=04/Sep/2018:21:12:12 service error 500, num=10 province=33' | python -m json.tool
返回的结果是
{
    "body": [],
    "matched": false
}
配置文件strategy.json和cfg.json中使用的是默认的配置文件

**Comment by tonglin0325** [comment]
http下面的check.go的matchedStrategy函数可能有点问题
