### ISSUE TITLE
配置StrategyConfig如下，但是未见采取数据上传到agent

### ISSUE THREAD

**Issue by gaomiup20** [didi/falcon-log-agent#2]
[
 
    {
        "id":1,
        "name":"servervice",
        "file_path":"/opt/xcloud-cm.016-10-17_0.info.log",
        "time_format":"dd/mmm/yyyy:HH:MM:SS",
        "pattern":"log,num=(\\d+)",
        "exclude":"unimport-request",
        "step":10,
        "tags":{
            "error":"服务器下线: null"
        },
        "func":"cnt",
        "degree":6,
        "comment":"我是备注"
    }
]
 tail -f /var/log/log-agent/INFO.log
2018-07-23 11:32:54.403516 INFO strategy/update.go:22 [1532316774]Update Strategy start
2018-07-23 11:32:54.403769 INFO strategy/get_config.go:22 load config success from cfg/strategy.json
2018-07-23 11:32:54.403929 INFO strategy/update.go:31 [1532316774]Get my Strategy success, num : [1]
2018-07-23 11:32:54.403944 INFO strategy/update.go:38 [1532316774]Update Strategy end
2018-07-23 11:32:54.408669 INFO worker/counter.go:254 Updating global count
2018-07-23 11:32:54.408698 INFO worker/counter.go:285 Update global count done, [del:0][update:0]
2018-07-23 11:32:54.435036 INFO patrol/patrol.go:21 agent mem used : 35MB, percent : 3%

**Comment by hongbin-li** [comment]
一样的，没上传，然后也没个文档！

**Comment by GaoJiasheng** [comment]
@gaomiup20 

有日志滚动吗？如果没有日志滚动，是不会有数据上报的。新版open-falcon已经支持了非周期数据，因此只有在采集到有效数据的时候，才会上报。

如果确认日志有滚动，可以check下配置的 文件路径、事件格式、正则表达式是否正确。用grep -P看一下，能否匹配出符合预期的日志。

回头我完善一个排错手册出来。

**Comment by GaoJiasheng** [comment]
加了一个api，可以用来check采集策略写的是否正确。

可以看下：https://github.com/didi/falcon-log-agent#%E6%A3%80%E9%AA%8C%E6%97%A5%E5%BF%97%E6%A0%BC%E5%BC%8F

**Comment by NICK-DUAN** [comment]
@gaomiup20 @hongbin-li 上面两位大哥解决了没有，我这个也没有上报，其他任何看起来都没有问题。

**Comment by GaoJiasheng** [comment]
> @gaomiup20 @hongbin-li 上面两位大哥解决了没有，我这个也没有上报，其他任何看起来都没有问题。

你看下我发的那个check的api，能自己定位不。

**Comment by dongdongkkk** [comment]
默认配置中
        "tags":{
            "provice" : "province=(\\s+)"
        },
代码中的处理逻辑是, 如果 tags 有配置, 那么 pattern 与 "province=(\\s+)"  同时匹配的时候才会上报. 

    "tags":{
        "error":"服务器下线: null"     你这个 不会匹配的  ,  考虑吧 整个 tags 删除吧 
    },



`        //处理tag 正则
        tag := map[string]string{}
        for tagk, tagv := range strategy.Tags {    //  有tags 配置 开始检查 
                var regTag *regexp.Regexp
                regTag, ok := strategy.TagRegs[tagk]
                if !ok {
                        dlog.Errorf("%s[get tag reg error][sid:%d][tagk:%s][tagv:%s]", w.Mark, strategy.ID, tagk, tagv)
                        return nil, nil
                }
                t := regTag.FindStringSubmatch(line)
                if t != nil && len(t) > 1 {
                        tag[tagk] = t[1]
                } else {
                        return nil, nil   // 不匹配  直接返回了 , 根本不上报
                }
        }`

**Comment by GaoJiasheng** [comment]
是的，如果配置了tag，就需要把tag抓取出来。否则上报到监控系统也很难标准化。
