### ISSUE TITLE
匹配中文问题

### ISSUE THREAD

**Issue by gaomiup20** [didi/falcon-log-agent#21]
➜  falcon-log-agent git:(master) ✗ curl -s -XPOST localhost:8003/check -d  'log=2018-09-06 10:31:10.094 [pool-4-thread-1] ERROR com.hxc_cloud.hxc_cloud.core.impl.TimerServiceImpl - Thread:40：---ERROR---分钟学时数据存储异常---ERROR- ' | python -m json.tool
{
    "body": [
        {
            "detail": {
                "pattern_": "\u5206\u949f\u5b66\u65f6\u6570\u636e\u5b58\u50a8\u5f02\u5e38",
                "time_": "2018-09-06 10:31:10"
            },
            "strategy": {
                "comment": "\u6211\u662f\u5907\u6ce8",
                "degree": 6,
                "exclude": "",
                "file_path": "/home/manzz/application/hxc_cloud_pro/log/error.log.2018-09-06.log",
                "func": "cnt",
                "id": 1,
                "name": "max_hour_ERROR",
                "parse_succ": false,
                "pattern": "\u5206\u949f\u5b66\u65f6\u6570\u636e\u5b58\u50a8\u5f02\u5e38",
                "step": 10,
                "tags": {},
                "time_format": "yyyy-mm-dd HH:MM:SS"
            }
        }
    ],
    "matched": true
}
➜  falcon-log-agent git:(master) ✗ cat cfg/strategy.json
[
    {
        "id":1,
        "name":"max_hour_ERROR",
        "file_path":"/home/manzz/application/hxc_cloud_pro/log/error.log.2018-09-06.log",
        "time_format":"yyyy-mm-dd HH:MM:SS",
        "pattern":"分钟学时数据存储异常",
        "exclude":"dial",
        "step":10,
        "tags":{
        },
        "func":"cnt",
        "degree":6,
        "comment":"我是备注"
    }
]
➜  falcon-log-agent git:(master) ✗ curl localhost:8003/cached
{"counters":{}}#

**Comment by GaoJiasheng** [comment]
cached只缓存最近一分钟的点，用来定位问题。可以打开debug看一下，有没有采集出点来。
