### ISSUE TITLE
匹配不成功,是什么原因呢?

### ISSUE THREAD

**Issue by leo-lu** [didi/falcon-log-agent#23]
cat cfg/strategy.json
[
    {
        "id":1,
        "name":"流量500错误数",
        "file_path":"/root/log/access.log",
        "time_format":"yyyy-mm-dd HH:MM:SS",
        "pattern":"error",
        "exclude":"",
        "step":5,
        "tags":{
        },
        "func":"cnt",
        "degree":6,
        "comment":"我是Error 500"
    }
]

curl -s -XPOST localhost:8003/check -d  'log=2017/12/01 12:12:06 service error 505, num=10 province=33' | python -m json.tool

{
    "body": [],
    "matched": false
}

**Comment by GaoJiasheng** [comment]
`"time_format":"yyyy-mm-dd HH:MM:SS",`
`2017/12/01 12:12:06 service error 505`

时间格式不对。。。

**Comment by leo-lu** [comment]
粗心了，谢谢！~
