### ISSUE TITLE
请教下多个策略时，且每个策略匹配出上百个不同的tags上传不及时

### ISSUE THREAD

**Issue by virtue1990** [didi/falcon-log-agent#26]

**Comment by virtue1990** [comment]
![image](https://user-images.githubusercontent.com/13484227/48829688-db597c00-edad-11e8-8265-bb114a0524be.png)
遇见的问题就是当我有多个策略去统计日志，会得出几百个不同的tags，从open-falcon的agent得到信息是10s发送一个push请求，但是我的多个策略并没有每次都上传。

**Comment by virtue1990** [comment]
也就是假如我heatbeat的这个metric，有时隔了20s才上传一次。这个是因为每次push的数据量有限制吗？

**Comment by GaoJiasheng** [comment]
> 也就是假如我heatbeat的这个metric，有时隔了20s才上传一次。这个是因为每次push的数据量有限制吗？

push的数据量没有限制，不过由于很多日志组件都是异步落盘，日志的落盘时间无法保证，log-agent会有一个延迟推送的机制，如果没有新的周期的时间戳落盘，当前周期的统计不会立刻推送，会稍等一定的时间。有新的周期的数据落盘，或者到达等待超时（这里依赖本地时间），再推送出去。
可以看一下你的日志是否同步落盘，再看下你日志的时间跟本地的时间是不是有差异。
