### ISSUE TITLE
几个问题请教一下

### ISSUE THREAD

**Issue by xiaofeng613n** [didi/falcon-log-agent#28]
1.这个适用采集业务程序日志么？能否代替flume类的日志采集器？
2.正则匹配的问题，对于日志量较大，正则表达式非常复杂的情况下，会不会影响采集的性能？造成cpu非常高？

**Comment by GaoJiasheng** [comment]
1、适合采集业务日志。不能代替flume类的日志采集器，因为这个agent只是根据用户配置的规则，进行采样计算，然后转化为监控的数据点，上报至open-falcon。
2、日志量较大，正则非常复杂的情况下，一定会影响采集的性能。但是更严重的是因为采集影响了服务的稳定性，因此建议对agent进行资源隔离。

@xiaofeng613n
