### ISSUE TITLE
为什么内存资源占用取的是堆内存？

### ISSUE THREAD

**Issue by wcc526** [didi/falcon-log-agent#29]
https://github.com/didi/falcon-log-agent/blob/67dce44aefd754ee93e183a575ce785c805b5582/common/proc/patrol/patrol.go#L41

为什么内存资源占用取的是堆内存？有办法查询swap空间的占用情况吗？如果swap占用比较多会影响机器的整体性能.

**Comment by GaoJiasheng** [comment]
> [falcon-log-agent/common/proc/patrol/patrol.go](https://github.com/didi/falcon-log-agent/blob/67dce44aefd754ee93e183a575ce785c805b5582/common/proc/patrol/patrol.go#L41)
> 
> Line 41 in [67dce44](/didi/falcon-log-agent/commit/67dce44aefd754ee93e183a575ce785c805b5582)
> 
>  ret := sts.HeapAlloc / 1024 / 1024 
> 为什么内存资源占用取的是堆内存？有办法查询swap空间的占用情况吗？如果swap占用比较多会影响机器的整体性能.

这个地方我回头优化下，读取proc获取下内存信息。

**Comment by GaoJiasheng** [comment]
额，这个我仔细看了下，这个地方不是来监控机器状态的。
这个patrol模块，是用来做agent自身资源限制的，当发现进程本身的资源超过一定的阈值，就会自动退出。
所以使用这个MemStats.HeapAlloc
