### ISSUE TITLE
【咨询】关于数据上报问题

### ISSUE THREAD

**Issue by yangyi19870212** [didi/falcon-log-agent#31]
**root@sinpedx00028:/home/work/open-falcon/falcon-log-agent# curl -s -XPOST localhost:8003/check -d  'log=Jan 30 14:10:49 sinpedx00028 ntpd[95200]: Soliciting pool server 45.125.1.20' | python -m json.tool
{
    "body": [
        {
            "detail": {
                "code": "sinpedx00028",
                "pattern_": "sinpedx00028",
                "time_": "Jan 30 14:10:49"
            },
            "strategy": {
                "comment": "\u6211\u662f\u5907\u6ce8",
                "degree": 6,
                "exclude": "",
                "file_path": "/var/log/syslog",
                "func": "cnt",
                "id": 1,
                "name": "\u6d41\u91cf500\u9519\u8bef\u6570",
                "parse_succ": true,
                "pattern": "sinpedx00028",
                "step": 10,
                "tags": {
                    "code": "sinpedx00028"
                },
                "time_format": "mmm dd HH:MM:SS"
            }
        }
    ],
    "matched": true
}
root@sinpedx00028:/home/work/open-falcon/falcon-log-agent# curl localhost:8003/cached
{"counters":{}}root@sinpedx00028:/home/work/open-falcon/falcon-log-agent# 

手工执行check能匹配上，但是实际运行一直取不到上报数据，能否请作者帮忙指导一下。谢谢**

**Comment by yangyi19870212** [comment]
{
        "id":1,
        "name":"流量500错误数",
        "file_path":"/home/work/myService/log/access.log",
        "time_format":"dd/mmm/yyyy:HH:MM:SS",
        "pattern":"service error 500, **num=(\\d+)**",
        "exclude":"unimport-request",
        "step":10,
        "tags":{
            "provice" : **"province=(\\s+)**"
        },
        "func":"cnt",
        "degree":6,
        "comment":"我是备注"
    },
而且加粗字体为何是\\而不是\，并且测试案例即使用\\也没有check出来。

**Comment by GaoJiasheng** [comment]
> {
> "id":1,
> "name":"流量500错误数",
> "file_path":"/home/work/myService/log/access.log",
> "time_format":"dd/mmm/yyyy:HH:MM:SS",
> "pattern":"service error 500, **num=(\d+)**",
> "exclude":"unimport-request",
> "step":10,
> "tags":{
> "provice" : **"province=(\s+)**"
> },
> "func":"cnt",
> "degree":6,
> "comment":"我是备注"
> },
> 而且加粗字体为何是\而不是\，并且测试案例即使用\也没有check出来。
> 作者是否方便留个联系方式，线下指导一下

这个反斜杠，是正则表达式的规则，可以看下正则表达式的语法。

**Comment by GaoJiasheng** [comment]
> **root@sinpedx00028:/home/work/open-falcon/falcon-log-agent# curl -s -XPOST localhost:8003/check -d 'log=Jan 30 14:10:49 sinpedx00028 ntpd[95200]: Soliciting pool server 45.125.1.20' | python -m json.tool
> {
> "body": [
> {
> "detail": {
> "code": "sinpedx00028",
> "pattern_": "sinpedx00028",
> "time_": "Jan 30 14:10:49"
> },
> "strategy": {
> "comment": "\u6211\u662f\u5907\u6ce8",
> "degree": 6,
> "exclude": "",
> "file_path": "/var/log/syslog",
> "func": "cnt",
> "id": 1,
> "name": "\u6d41\u91cf500\u9519\u8bef\u6570",
> "parse_succ": true,
> "pattern": "sinpedx00028",
> "step": 10,
> "tags": {
> "code": "sinpedx00028"
> },
> "time_format": "mmm dd HH:MM:SS"
> }
> }
> ],
> "matched": true
> }
> root@sinpedx00028:/home/work/open-falcon/falcon-log-agent# curl localhost:8003/cached
> {"counters":{}}root@sinpedx00028:/home/work/open-falcon/falcon-log-agent#
> 
> 手工执行check能匹配上，但是实际运行一直取不到上报数据，能否请作者帮忙指导一下。谢谢**

你可以参考下这个issue我的回答：https://github.com/didi/falcon-log-agent/issues/11

**Comment by GaoJiasheng** [comment]
然后也可以看下这个issue中那位同学查看的日志情况，可以有效地协助你定位问题。

**Comment by GaoJiasheng** [comment]
关于这个问题，可以都在 https://github.com/didi/falcon-log-agent/issues/11 讨论哈，这个issue我就关掉了。
