### ISSUE TITLE
大量metric上报

### ISSUE THREAD

**Issue by NICK-DUAN** [didi/falcon-log-agent#33]
这个插件可以做到扫描指定位置的日志文件，然后上报到falcon。  
我想咨询一下，如果一个文件里面有**大量且不重复**的metric，此时配置strategy.json的话就需要每个metric都配一下，那么这个工作量也很大，感觉也不合理。  
有没有合适的方式扫描到一个metric就上报一个metric，而且这里的name对应falcon的metric，但是还是需要自己配，有没有可能直接上报falcon的metric。  
具体想法是：扫描到文件里面的metric，那么上报这个metric（metric**大量且不重复**）

**Comment by GaoJiasheng** [comment]
可以用同一个固定的metric，然后把你这些“大量且不重复”的字段，配置到tag里。
基本就可以满足了。

@NICK-DUAN
