### ISSUE TITLE
日志报错（producer error）数据不上传，求大神解救！

### ISSUE THREAD

**Issue by aircyz** [didi/falcon-log-agent#39]
大神好：
我使用falcon-log-agent的时候出现一个问题，配置文件strategy.json中配置:
"id":1,
        "name":"agent-jm-log-INFO",
        "file_path":"xxxxxxxxxxxxxx/jm.log",
        "time_format":"yyyy/mm/dd HH:MM:SS",
        "pattern":"INFO",
        "exclude":"",
        "step":10,
        "tags":{
        },
        "func":"cnt",
        "degree":6,
        "comment":""

然而并不上传数据，我看了下日志出现错误日志：
2019-05-27 15:05:16.078068 ERROR sample_log/sample_log.go:83 [worker][file:/opt/dmeeting/dm-project/logs/jm-manager/jm.log][num:10][id:6][producer error][sid:1] : cannot get timestamp:[sname:agent-jm-log-Error][sid:1][timeFormat:2006/01/02 15:04:05]. log_num : 1
2019-05-27 15:05:16.078084 ERROR sample_log/sample_log.go:83 [worker][file:/opt/dmeeting/dm-project/logs/jm-manager/jm.log][num:10][id:9][producer error][sid:1] : cannot get timestamp:[sname:agent-jm-log-Error][sid:1][timeFormat:2006/01/02 15:04:05]. log_num : 1

说什么producer error，但是我用curl -s -XPOST localhost:8003/check -d 'log=2019/05/18 12:12:12 INFO, num=10 province= ' | python -m json.tool
是可以正常返回数据的
 "body": [
        {
            "detail": {
                "pattern_": "INFO",
                "time_": "2019/05/18 12:12:12"
            },
            "strategy": {
                "comment": "",
                "degree": 6,
                "exclude": "",
                "file_path": "/xxxxxxxxxx/jm.log",
                "func": "cnt",
                "id": 1,
                "name": "agent-jm-log-Error",
                "parse_succ": true,
                "pattern": "INFO",
                "step": 10,
                "tags": {},
                "time_format": "yyyy/mm/dd HH:MM:SS"
            }
        }
    ],
    "matched": true

然后我就无语了

排查的过程中我修改了配置，即上面配置文件中修改了"pattern":"INFO",  改成"pattern":"Total=(\\d+)",  并且修改成对应的agent的log路径，则完全正常，没有错误日志，也正常出现图形，所以我怀疑是"pattern":"INFO", 这个问题，我换成了"pattern":"ERROR",也不行，我想问下pattern
这到底该如何配置，我想统计INFO日志（计数就可以cnt），和统计ERROR错误日志，还请大神指点一二！！！！

**Comment by itxx00** [comment]
检查/opt/dmeeting/dm-project/logs/jm-manager/jm.log  这个里面是否所有行都符合"time_format": "yyyy/mm/dd HH:MM:SS"  ？
