### ISSUE TITLE
自定义endpoint，建议支持自定义endpoint。

### ISSUE THREAD

**Issue by superbikini** [didi/falcon-log-agent#41]

**Comment by superbikini** [comment]
我是一个门外汉，编程语言都不怎么看的明白。
但是这个需求比较简单，我在源码中简单加了2行，实现除IP和HOST以外的自定义endpoint
func GetEndpoint(endpoint string) (string, error) {
	if strings.ToUpper(endpoint) == "IP" {
		return LocalIP()
	}

	if strings.ToUpper(endpoint) == "HOST" {
		return LocalHostname()
	}

	// endpoint,自定义部分
	endpoint = endpoint
	return endpoint, nil
}

**Comment by GaoJiasheng** [comment]
这个不太建议，这里的endpoint来源于配置文件，可选IP和主机名。
因为endpoint是有具体含义的，代表的就是某条监控数据的产生端，因此还是比较建议用IP和主机名。
不过生产环境，确实有改变endpoint的需求，比如某一台机器采集的多条机器的业务信息，需要分别指定endpoint。
但是这种需求，你这种方式也是无法支持的，你这种方式直接改endpoint字段，整个agent都使用这一个endpoint，也没办法做到endpoint的细分。如果仅仅为了改名，不建议。
