### ISSUE TITLE
正则未匹配到行，cnt计算方法，无法记录为0.

### ISSUE THREAD

**Issue by superbikini** [didi/falcon-log-agent#42]
正则未匹配到行，cnt计算方法，无法记录为0.
因为falcon-server通过超过阈值报警，低于阈值恢复。
我们在扫面日志错误关键字时，正常情况下，是匹配不带关键字的。所以希望cnt计算方法可以记录为0，便于falcon-server后续报警策略

**Comment by GaoJiasheng** [comment]
如果你们用falcon-plus的话，有一个nodata的组件，专门用来补0的。agent不太适合做补0的事，原因有二：
- 性能
- 指标无法过期（设定过期时间也并不是一个好的选择）
