### ISSUE TITLE
PosterLoop slice make fix?

### ISSUE THREAD

**Issue by cyongxue** [didi/falcon-log-agent#43]
// PosterLoop to start post loop
// 循环推送，10s一次
func PosterLoop() {
	dlog.Info("PosterLoop Start")
	go func() {
		for {
			select {
			case p := <-pushQueue:
				points := make([]*FalconPoint, 0)
				points = append(points, p)
			DONE:
				for {
					select {
					case tmp := <-pushQueue:
						points = append(points, tmp)
						continue
					default:
						break DONE
					}
				}
				//先推到cache中
				PostToCache(points)
				//开一个协程，异步发送至odin-agent
				go postToFalconAgent(points)
			}
			time.Sleep(10 * time.Second)
		}
	}()
}

this code maybe is better for：

points := make([]*FalconPoint, len(pushQueue))  

or len(pushQueue) + x

**Comment by GaoJiasheng** [comment]
I think cannot, `pushQueue` is a queue for collecting the data points which were pushed from other goroutine.
During the `for` loop which get the points from queue continously, there may be other input writed into the queue, so if we structed the points size, it may cannot save all the points from queue.
any idea?
