### ISSUE TITLE
Inner machine Security risks for listen 0.0.0.0

### ISSUE THREAD

**Issue by cyongxue** [didi/falcon-log-agent#44]
// Start http api
func Start() {
	router := gin.Default()
	router.GET("/health", func(c *gin.Context) {
		c.JSON(http.StatusOK, "ok")
	})
	router.GET("/strategy", func(c *gin.Context) {
		c.JSON(http.StatusOK, strategy.GetListAll())
	})

	router.GET("/cached", func(c *gin.Context) {
		c.String(http.StatusOK, worker.GetCachedAll())
	})

	router.POST("/check", func(c *gin.Context) {
		log := c.PostForm("log")
		c.JSON(http.StatusOK, CheckLogByStrategy(log))
	})

	router.Run(fmt.Sprintf("0.0.0.0:%d", g.Conf().Http.HTTPPort))
}

**Comment by GaoJiasheng** [comment]
https://github.com/didi/falcon-log-agent/pull/46
