### ISSUE TITLE
为啥不把falcon-log-agent的功能合并到open-falcon-agent服务里

### ISSUE THREAD

**Issue by nondevops** [didi/falcon-log-agent#45]
为啥不把falcon-log-agent的功能合并到open-falcon-agent服务里，这样子的话，每个实例都得要安装2个agent，一个采集常规数据，一个采集日志。感觉太浪费资源了

**Comment by GaoJiasheng** [comment]
当时的考虑是log-agent的资源占用弹性很大，一旦策略复杂或日志量太大，都会影响系统稳定性。
因此考虑把log-agent单独拿出来做单独的资源限制，目的是不要因为日志的性能限制而影响了基础监控指标的采集。
