### ISSUE TITLE
常规的nginx log 能收集吗？

### ISSUE THREAD

**Issue by linydquantil** [didi/falcon-log-agent#47]
日志格式类似这样:
10.1.0.124 - - [24/Apr/2020:07:06:11 +0000] "PATCH /api/DN/checkdns. HTTP/1.1" 200 1600 "-" "python-requests/2.23.0"
@GaoJiasheng  麻烦帮忙确认一下

**Comment by GaoJiasheng** [comment]
可以的，有固定的时间就能采集。写正则就行了。
