### ISSUE TITLE
作者可以帮个忙吗，像2021-04-09--0.log这个的文件如何改写动态路径，谢谢

### ISSUE THREAD

**Issue by wangxiajian** [didi/falcon-log-agent#49]

**Comment by GaoJiasheng** [comment]
`--0` 这部分是个序号吗？这种按大小切割的日志目前没办法支持，有两种建议你可以选择：
1、把你的写入的日志文件名，写成固定的，比如XXapp.log，然后根据时间或者大小去做切割。
2、把按时间切分的粒度做的细一点，比如到小时级别。去掉`--0`这种时间无关的序号。
